version: '3.3'
services:
  frontend-deps:
    build: '.'
    volumes:
      - 'node_modules:/node_modules'

  frontend-watch:
    image: 'node:9-alpine'
    working_dir: '/frontend'
    depends_on:
      - 'frontend-deps'
    environment:
      - 'PATH=$PATH:/root/.node_modules/.bin/'
    volumes:
      - './frontend:/frontend'
      - 'node_modules:/root/.node_modules'
    entrypoint: 'yarn run watch'

  frontend-server:
    image: 'node:9-alpine'
    working_dir: '/frontend'
    depends_on:
      - 'frontend-deps'
    environment:
      - 'PATH=$PATH:/root/.node_modules/.bin/'
    volumes:
      - './frontend:/frontend'
      - 'node_modules:/root/.node_modules'
    entrypoint: 'yarn run server'
    ports:
      - '8080:8080'

volumes:
  node_modules:
